### PR TITLE
4 new live templates

### PR DESCRIPTION
**Pull request by jmfayard**
- **``key``**: "declare a constant KEY_XXX for a bundle" 
- **``var``**: "declare a android-style int constant" 
- **``logm``**: "Log.d(TAG, $METHOD_NAME$() was called with args : name1=[value1] name2=[value2} ..)"
- **``logr``**: "Log.d(TAG, $METHOD_NAME$() returned $result$") ; return $result" 

I especially like `logm`

### CODE REVIEW

**Comment by keyboardsurfer** [comment]
Shouldn't `var` rather be a `const`?
Please use the `listCurrentTemplates.sh` to generate the documentation in order to keep consistency.

**Comment by jmfayard** [comment]
Yes, `const` is better. 
Also I have renamed `LogTag` to `logt` for consistency

**Comment by jmfayard** [comment]
@keyboardsurfer is it ok now?

**Comment by keyboardsurfer** [comment]
From the content side, yes.
As agreed, please squash the commits to keep history cleaner.

**Comment by jmfayard** [comment]
obsoloted by pull request #10

**Pull request closed without merging**
